name: Build PDF Combine Utility

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Create Directories
      run: |
        mkdir .img
        mkdir .font

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pdf-combine-utility
        path: dist/main.exe